set shell := ["zsh", "-uc"]
set dotenv-load := true

target       := "thumbv7em-none-eabihf"
chip         := "STM32G431CBUx"
profile      := "release"                   # release or debug
defmt_level  := "info"                     # default DEFMT_LOG
default_bin  := "stm32-g431-cbu6"           # fallback

# List
default:
    @just --list

# Build default
build bin=default_bin profile=profile:
    DEFMT_LOG="${DEFMT_LOG:-{{defmt_level}}}" \
    cargo build --{{profile}} --bin {{bin}}

# Run flash + rtt via cargo runner
run bin=default_bin profile=profile:
    cargo clean 
    DEFMT_LOG="${DEFMT_LOG:-{{defmt_level}}}" \
    cargo run --{{profile}} --bin {{bin}}

# Flash via cargo flash
flash bin=default_bin:
    cargo flash --chip {{chip}} --release --target {{target}} --bin {{bin}}

# Rtt
rtt:
    cargo embed

# Cargo size
size bin=default_bin profile=profile:
    cargo size --target {{target}} --{{profile}} --bin {{bin}} -- -A

# Cargo clean
clean:
    cargo clean

# Cargo fmt + Cargo clippy -D warnings
fmt:
    cargo fmt
    cargo clippy --target {{target}} -- -D warnings

# Runner bin + loglevel
run-log bin=default_bin level="debug" profile=profile:
    DEFMT_LOG="{{level}}" \
    cargo run --{{profile}} --bin {{bin}}
