[package]
name = "socketcan-node"
version = "0.1.0"
edition = "2024"

[dependencies]
korri-n2k = { version = "0.7.0", features = [
  "tokio",
] }
shared-core = { path = "../../shared-core", default-features = false, features = [
  "tokio",
] }
socketcan = { version = "3.6", features = ["tokio"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
anyhow = "1.0"

[profile.release]
lto = false
codegen-units = 1
panic = "abort"
opt-level = "s"

# [target.armv7-unknown-linux-gnueabihf]
# linker = "arm-linux-gnueabihf-gcc"
